# Generated by Django 6.0.5 on 2026-05-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('shift_assigned', 'Shift Assigned'), ('shift_published', 'Shift Published'), ('shift_cancelled', 'Shift Cancelled'), ('shift_reminder', 'Shift Reminder'), ('swap_request', 'Swap Request'), ('swap_accepted', 'Swap Accepted'), ('swap_rejected', 'Swap Rejected'), ('swap_approved', 'Swap Approved'), ('time_off_submitted', 'Time Off Submitted'), ('time_off_approved', 'Time Off Approved'), ('time_off_rejected', 'Time Off Rejected')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
